sudo: false
language: cpp
addons:
  apt:
    packages:
      - g++-multilib
compiler:
  - clang
before_script:
  - cd ..
  - git clone --depth=1 --branch=1.7-dev https://github.com/alliedmodders/sourcemod
  - git clone --depth=1 --branch=master https://github.com/alliedmodders/ambuild
  - cd ambuild
  - python setup.py install --user
  - cd $TRAVIS_BUILD_DIR
  - git fetch --unshallow
script:
  - mkdir build
  - cd build
  - python ../configure.py --enable-optimize --enable-debug
  - ~/.local/bin/ambuild
after_success:
  - python ../upload.py
